# Lynx theme for Hugo

name = "lynx"
license = "MIT"
licenselink = "https://github.com/GiovsTech/lynx/blob/master/LICENSE"
description = "A links page theme for Hugo built with Tailwind CSS."

homepage = "https://github.com/GiovsTech/lynx/"
demosite = "https://links.giovstechs.it"

tags = ["minimal", "responsive", "dark mode", "dark", "light", "tailwind", "personal"]
features = ["dark mode", "emoji"]

[author]
  name = "GiovsTechs"
  homepage = "https://giovstechs.it"
